model_params:
  bert_model_name: "bert-base-uncased"
  embedding_dim: 768
  lstm_input_dim: 5
  lstm_units: [128, 64]
  dropout_rate: 0.2
  gnn_node_features: 64
  gnn_hidden_channels: 64
  num_regions: 5
  temporal_window: 7 # Days to look back
  learning_rate: 0.001
  batch_size: 32
  epochs: 1
  city_mapping:
    Bangalore: 0
    Chennai: 1
    Kolkata: 2
    Mumbai: 3
    Delhi: 4
  pharmacy_feature_cols: 
    - fever_medicine_sales
    - cough_medicine_sales
    - diarrhea_medicine_sales
    - antibiotic_sales
    - painkiller_sales

data_params:
  num_samples: 1000
  pharmacy_feature_dim: 5
  outbreak_threshold: 0.5

paths:
  synthetic_data: "data/generated_dataset/synthetic_outbreak_data.csv"
  real_data: "project_root/data/PharmacyFabricated/synthetic_pharmacy_sales.csv"
  model_save_dir: "saved_models/outbreak_predictor_v1"
